version: "3"

services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mosquitto-iot
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - network-name

networks:
    network-name:
      name: uniovi
